CREATE TABLE [dbo].[LogETLJob]
(
  LogETLJobId INT NOT NULL Identity(1,1) Constraint PK_LogETLJob PRIMARY KEY,
  PipelineId UNIQUEIDENTIFIER NOT NULL CONSTRAINT UC_LogETLJob_PipelineId UNIQUE,
  PipelineName VARCHAR(400),
  PLStartTime DATETIME2(3),
  PLEndTime DATETIME2(3),
  CreatedOn DATETIME2(3) DEFAULT GETDATE()
);
GO