CREATE TABLE [dbo].[LogETLJob]
(
  LogETLJobId INT NOT NULL Identity(1,1) CONSTRAINT PK_LogETLJob PRIMARY KEY,
  PipelineId UNIQUEIDENTIFIER NOT NULL CONSTRAINT UC_LogETLJob_PipelineId UNIQUE,
  PipelineName VARCHAR(400),
  PLStartTime DATETIME2(7),
  PLEndTime DATETIME2(7),
  CreatedOn DATETIME2(7) CONSTRAINT DF_LogETLJob_CreatedOn DEFAULT GETDATE(),
  LastUpdatedOn DATETIME2(7) CONSTRAINT DF_LogETLJob_LastUpdatedOn DEFAULT GETDATE()
);
GO